module.exports = function(grunt){
  grunt.initConfig({
    sass:{
      options:{
        style:"compressed"
      },
      dist:{
        files:{
          "assets/css/style.css":"assets/sass/style.scss",
          "admin/assets/css/style.css":"admin/assets/sass/style.scss"
        }
      }
    },
    uglify:{
      my_target:{
        files:{
          "assets/js/script.min.js":"assets/js/script.js",
          "admin/assets/js/script.min.js":"admin/assets/js/script.js"
        }
      }
    },
    watch:{
      options:{
        livereload:460
      },
      sass:{
        files:["assets/sass/style.scss","admin/assets/sass/style.scss"],
        tasks:"sass",
        reload:false
      },
      css:{
        files:["assets/style/style.css","admin/assets/style/style.css"],
        reload:true
      },
      js_min:{
        files:["assets/js/script.js","admin/assets/js/script.js"],
        tasks:"uglify",
        reload:false
      },
      js:{
        files:["assets/js/script.min.js","admin/assets/js/script.min.js"],
        reload:true
      },
      php:{
        files:"**/*.php",
        reload:true
      }
    }
  });
  grunt.loadNpmTasks("grunt-contrib-sass");
  grunt.loadNpmTasks("grunt-contrib-uglify");
  grunt.loadNpmTasks("grunt-contrib-watch");

  grunt.registerTask("default",["watch"]);
}
